# Generated by Django 4.1.7 on 2023-03-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
